Repository Arsenic-ATG/Tetris, pull requests merged in 2022-08, with the labels that each got.

#13 Add basic scoring system
  build/index.js
  build/index.wasm
  src/game.cpp
  src/game.hpp
Labels: enhancement

#17 Fix: fix pause and quit control
  build/index.js
  build/index.wasm
  src/app.cpp
  src/game.cpp
  src/game.hpp
Labels: bug, enhancement, UI

#20 Fix: Anti-clockwise rotation
  src/game.cpp
Labels: enhancement

#25 Styiling
  build/.styles.css.swp
  build/index.html
  build/styles.css
Labels: enhancement, UI

#26 feat: implement basic leveling system
  src/game.cpp
  src/game.hpp
Labels: enhancement
